name: ipstack
author: ericmartineau
version: 0.5.1+1
homepage: https://github.com/SunnyApp/ipstack
description: Uses ipstack.com service to retrieve details based on the user's ip address.
environment: 
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=1.17.0'
dependencies: 
  http: ^0.13.5
  meta: ^1.9.0
  pedantic: ^1.11.1
  flutter: 
    sdk: flutter
dev_dependencies: 
  dartxx: 
    path: /Users/ericm/reliveit/checkout/ericmartineau/dartxx
  flutter_test: 
    sdk: flutter
